server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fabcars?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false
    #url: jdbc:mysql://192.168.31.103:3306/fabcars?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    mode: HTML
    cache: false
    encoding: UTF-8
mybatis:
  configuration:
    default-statement-timeout: 3000
    map-underscore-to-camel-case: true
    use-generated-keys: true
    cache-enabled: true
  mapper-locations: classpath:mybatis/*.xml
  type-aliases-package: com.example.fabricfabcar.domain
